# Default values for glowroot-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # quick fix patched image till official glowroot image works again
  repository: novumrgi/glowroot-central
  tag: 0.13.7
  pullPolicy: Always

service:
  http:
    type: ClusterIP
    port: 4000
  collector:
    type: ClusterIP
    port: 8181
    #loadBalancerIP:
    #nodePort:
    #externalTrafficPolicy:
    #externalIPs:
    annotations:
    
glowroot:
  cassandra:
    # can be any 32 character hex string
    symmetricEncryptionKey: f8b62a6a4bd37abcc95e2f15d69c7b91
  ui:
    contextPath:
  admin:
    anonymousUser: true
    general:
      displayName: ""
    users:
      #- name:
      #  password:
      #  roles:
      #    - test
    roles:
      # administrator role is always created
      #- name: Administrator
      #  permissions:
      #    - admin
      #    - agent:*:config
      #    - agent:*:error
      #    - agent:*:incident
      #    - agent:*:jvm
      #    - agent:*:syntheticMonitor
      #    - agent:*:transaction
    web:
      sessionTimeoutMin: 30
      sessionCookieName: GLOWROOT_SESSION_ID
    storage:
      responseTimeJvmGaugeHours:
        oneMinAggregates: 48
        fiveMinAggregates: 336
        thirtyMinAggregates: 720
        fourHourAggregates: 720
      queryServiceCallDataHours:
        oneMinAggregates: 48
        fiveMinAggregates: 168
        thirtyMinAggregates: 720
        fourHourAggregates: 720
      profileDataHours:
        oneMinAggregates: 48
        fiveMinAggregates: 168
        thirtyMinAggregates: 720
        fourHourAggregates: 720
      traceDataHours: 336
    ldap:
      enabled: false
      #connection:
        #host:
        #port:
        #ssl:
        #follow:
        #bindDN:
        #bindPw:
      #structure:
        #userBaseDN:
        #userSearchFilter:
        #groupBaseDN:
        #groupSearchFilter:
      #mapping:
        #- ldapGroupDN:
        #  glowrootRoles:
        #    - "rolename"
    smtp:
      enabled: false
      #host: mailhost
      #port: 587
      #connectionSecurity: ssl-tls
      #username:
      #password:
      #fromEmailAddress:
      #fromDisplayName:


cassandra:
  # see cassandra helm chart for more detailed description
  dbUser:
    user: cassandra
    password: password
  keyspace:

ingress:
  agent:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - glowroot-agent.local.com
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - glowroot.local.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nameOverride: ""
fullnameOverride: ""
