apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus2.fullname" . }}
  labels:
    {{- include "nexus2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "nexus2.selectorLabels" . | nindent 4 }}
